### ISSUE TITLE
Which version of caffe?

### ISSUE THREAD

**Issue by zhaozj89** [chenxi116/TF-deeplab#1]
I am using the windows caffe python3.5 vs2015 release version. But it reports

![image](https://cloud.githubusercontent.com/assets/5336612/23820256/cb421f1c-064f-11e7-98b4-11c5c66904c1.png)

Thanks!

**Comment by chenxi116** [comment]
Please try this branch of my caffe: https://github.com/chenxi116/caffe/tree/feature/20160617_cb_softattention
Basically it integrates the DeepLab v2 code into a more recent caffe. Using the original DeepLab v2 code released by the DeepLab author should also work.

**Comment by zhaozj89** [comment]
Could you send me a copy of `ResNet101_init.tfmodel`. I use windows, and it is hard for me to compile a customized caffe. Thanks very much!

**Comment by chenxi116** [comment]
I might be able to do that later, but not today.
I just thought of another trick that might work. Since the interp layers in deeplab do not have weights, maybe you can try edit the deploy.prototxt and remove all interp layers.

**Comment by zhaozj89** [comment]
Great thanks. I will try that first.
