### ISSUE TITLE
Converting caffemodel to npy file error

### ISSUE THREAD

**Issue by m-Just** [chenxi116/TF-deeplab#2]
When I ran `python caffemodel2npy.py deploy.prototxt ../deeplab/ResNet101/init.caffemodel/model/ResNet101_init.npy`, an error occurred as the following.

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0725 18:40:56.169318  9626 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0725 18:40:56.169384  9626 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0725 18:40:56.169395  9626 _caffe.cpp:125] Net('deploy.prototxt', 1, weights='../deeplab/ResNet101/init.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 15:16: Message type "caffe.LayerParameter" has no field named "interp_param".
F0725 18:40:56.173895  9626 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: deploy.prototxt
*** Check failure stack trace: ***
Abort (core dumped)

What can the problem possibly be?

**Comment by chenxi116** [comment]
Most likely it's because your caffe does not support deeplab layers. You can use mine: https://github.com/chenxi116/caffe/tree/feature/20160617_cb_softattention

**Comment by m-Just** [comment]
It worked. Thanks bunches!

**Comment by peach-xiao** [comment]
> 成功了。非常感谢！

非常抱歉这么多年了还来打扰您，我现在安装caffe版本，很多依赖包都更新了没能成功安装caffe，希望能从您这里要一份转换后的ResNet101_init.tfmodel和ResNet101_train.tfmodel，如果可以提供的话，感激不尽！

**Comment by peach-xiao** [comment]
> 很可能是因为你的 caffe 不支持 deeplab 层。你可以使用我的：https://github.com/chenxi116/caffe/tree/feature/20160617_cb_softattention

您好！我尝试转换对应的预训练文件，但是受限于很多依赖包都更新了没能成功安装caffe，希望能从您这里要一份转换后的ResNet101_init.tfmodel和ResNet101_train.tfmodel，如果可以提供的话，感激不尽！

**Comment by m-Just** [comment]
> > 成功了。非常感谢！
> 
> 非常抱歉这么多年了还来打扰您，我现在安装caffe版本，很多依赖包都更新了没能成功安装caffe，希望能从您这里要一份转换后的ResNet101_init.tfmodel和ResNet101_train.tfmodel，如果可以提供的话，感激不尽！

抱歉，太过久远，已经不知道去哪了。。不过为什么要用这么老的模型？

**Comment by peach-xiao** [comment]
想复现一篇CVPR2020年提出的模型，需要自己转换这个预训练权重文件，我一直安装这个caffe没有成功...谢谢大哥的回复，我再试试其他的方案&nbsp;


小果果^ω^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月19日(星期一) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenxi116/TF-deeplab] Converting caffemodel to npy file error (#2)














   
成功了。非常感谢！
  
非常抱歉这么多年了还来打扰您，我现在安装caffe版本，很多依赖包都更新了没能成功安装caffe，希望能从您这里要一份转换后的ResNet101_init.tfmodel和ResNet101_train.tfmodel，如果可以提供的话，感激不尽！
  
抱歉，太过久远，已经不知道去哪了。。不过为什么要用这么老的模型？

**Comment by m-Just** [comment]
> 想复现一篇CVPR2020年提出的模型，需要自己转换这个预训练权重文件，我一直安装这个caffe没有成功...

不用谢。感觉可以问下你想复现的这篇论文的作者？

**Comment by weizheng-113** [comment]
> 想复现一篇CVPR2020年提出的模型，需要自己转换这个预训练权重文件，我一直安装这个caffe没有成功...谢谢大哥的回复，我再试试其他的方案&nbsp;
> 
> 
> 小果果^ω^
> ***@***.***
> 
> 
> 
> &nbsp;
> […](#)

你好，您找到这个转换后的模型ResNet101_init.tfmodel和ResNet101_train.tfmodel了吗，可以分享一下吗
